export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const CURRENT_USER = 'CURRENT_USER';
export const CURRENT_USER_Fail = 'CURRENT_USER_Fail';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_USERS = 'GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const FAIL_USER = 'FAIL_USER';
export const ADD_USER ='ADD_USER';